name: Semgrep SAST Scan

on:
  push:
    branches: [ "master", "main" ]

jobs:
  semgrep-scan:
    name: Run Semgrep
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep SAST
        run: semgrep scan --config auto .
